version: "3.8"
services:
    localstack:
        image: localstack/localstack-pro:4
        ports:
            - "4566:4566"
        environment:
            - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN}
            - ACTIVATE_PRO=1
